# Generated by Django 6.0 on 2025-12-19 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.BigIntegerField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
